accounts/urls.py
from django.urls import path
from . import views
 
app_name = 'accounts'
 
urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout')
    ]

flipr/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('',include('jobs.urls')),
    path('allauth/', include('allauth.urls')),
]

jobs/urls.py
from django.urls import path
from . import views
 
app_name = 'jobs'
 
urlpatterns = [
    path('', views.home, name='home'),
    path('result/', views.jobsresult, name='result'),
    path('profile/', views.profile, name='profile'),
    path('about/', views.about, name='about'),
    path('detail/<int:pk>/', views.detail, name='detail'),
    path('apply/<int:job_id>/', views.apply, name='apply'),
    path('profiledata/', views.profiledata, name='profiledata'),
    # path('import/', views.import_view, name='import'),
    ]

accounts/models.py
from django.db import models

# Create your models here.

jobs/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class JobPost(models.Model):
    company	= models.CharField(max_length=200,null=True,blank=True)
    joblocation_address = models.CharField(max_length=200,null=True,blank=True)
    jobtitle = models.CharField(max_length=200,null=True,blank=True)
    link=models.URLField(max_length = 200,default=None,null=True)

    class Meta:
        managed = True
        db_table = 'job_post'


class JobApply(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    jobid = models.ForeignKey(JobPost,on_delete=models.CASCADE)

    class Meta:
        managed=True
        db_table = 'job_applied'
        
    

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login,logout

def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('/')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form': form})
 
 
def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user,backend='django.contrib.auth.backends.ModelBackend')
            return redirect('/')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form': form})


def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return render(request, 'jobs/index.html')

jobs/views.py
from django.shortcuts import render, redirect
from itertools import islice
import os
import openpyxl
from .models import JobPost,JobApply
from django.http import HttpResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponseRedirect
import requests
from bs4 import BeautifulSoup
from jobs.jp import job_data
from django.views.decorators.csrf import csrf_exempt

# Create your views here.
# def home(request):
#     data = JobPost.objects.all()
#     # user_list = User.objects.all()
#     page = request.GET.get('page')

#     paginator = Paginator(data, 10)
#     try:
#         context = paginator.page(page)
#     except PageNotAnInteger:
#         context = paginator.page(1)
#     except EmptyPage:
#         context = paginator.page(paginator.num_pages)

#     # context={'data':data}
#     return render(request, 'jobs/index.html',{'context':context})

def home(request):
    return render(request, 'jobs/index.html')

def jobsresult(request):
 
 
    if request.method == 'POST':
        job = request.POST['jobp']
        naukri=job
        location = request.POST['jobl']
 
     
        job = job.strip()
        j = job.title().strip()
        items = j.split(' ')
        location = location.strip()
        
        job = job.replace(' ', '+')
 
        url ='https://www.indeed.co.in/jobs?q='+job+'&l='+location+'&start='
 
        id,x,y,z,a,b= job_data(url,items)
        
 
        data = list(zip(id,x,y,z,a,b))

        print(len(data))
        page = request.GET.get('page')

        paginator = Paginator(data, 10)
        try:
            dat = paginator.page(page)
        except PageNotAnInteger:
            dat = paginator.page(1)
        except EmptyPage:
            dat = paginator.page(paginator.num_pages)


        if len(x)>0:
            
            context ={
                'data':dat,
                'location':location,
                'job':naukri,
                 
            }
        
        else:
            context ={
                'message':'No Jobs Found..!',
                 
            }
 
 
        return render(request,'jobs/index.html',context)
     
    return render(request,'jobs/index.html')



def profile(request):
    user=request.user
    jobs=JobApply.objects.filter(user=user)
    # print(jobs)
    return render(request,'jobs/profile.html',{'jobs':jobs})
    # return render(request, 'jobs/about.html')

def about(request):
    return render(request, 'jobs/about.html')

def detail(request,pk):
    job = JobPost.objects.filter(id=pk).first()
    print(job)
    return render(request,'jobs/detail.html',{'job':job})

def apply(request,job_id):
    print(job_id)
    if request.method=="POST":
        user=request.user
        job=JobPost.objects.filter(id=job_id).first()
        JobApply(user=user,jobid=job).save()
        # jobs=JobApply.objects.filter(user=user)
        # print(jobs)
        # return render(request,'jobs/profile.html',{'jobs':jobs})
        return HttpResponseRedirect("/jobs/home/")


def profiledata(request):
    if request.method == 'POST' and request.is_ajax():
        user=request.user
        company = request.POST.get('company', False)
        location = request.POST.get('location', False)
        title = request.POST.get('title', False)
        link=request.POST.get('link', False)
        job=JobPost(company=company,joblocation_address=location,jobtitle=title,link=link)
        job.save()
        JobApply(user=user,jobid=job).save()

        return HttpResponse(status=201)
        


# def import_view(request):
#     cwd = os.getcwd()
#     file_to_read = cwd+'\\file\\sample.xlsx'
#     f = openpyxl.load_workbook(file_to_read)
#     sheet_obj = f.active
#     max_row = sheet_obj.max_row
#     max_col =sheet_obj.max_column
    
#     fList= []
#     for i in range(2, max_row):
#         templist = []
#         for j in range(1,max_col):
#             templist.append(sheet_obj.cell(row=i,column=j).value)
#         fList.append(templist)
   
#     batch_size = 1000
#     objs = (JobPost(company=data[0],education=data[1],experience=data[2],industry=data[3],jobdescription=data[4],jobid=data[5],joblocation_address=data[6],jobtitle=data[7],numberofpositions=data[8],payrate=data[9],postdate=data[10],site_name=data[11],skills=data[12],uniq_id=data[13]) for data in fList)
#     while True:
#         batch = list(islice(objs, batch_size))
#         if not batch:
#             break
#         JobPost.objects.bulk_create(batch, batch_size)
    
#     return HttpResponse('Success')
# import_view()
#         

templates/accounts/login.html
{% extends "accounts/base.html" %}
{% load static %}

{% block content %}
<div class="container-fluid ">
    <div class="row logrow ">
        <div class="col-md-6 col-lg-4 mt-3 bg-img">
            <h1>Log In</h1>
            <div class="form">
                <form id="login" action="{% url 'accounts:login' %}" method="post">
                    {% csrf_token %}
                    {{ form.as_p }}

                    <a href="{% url 'accounts:signup' %}">Dont have an account?</a>

                    <input type="submit" class="btn btn-dark" value="Log In">

                </form>

                <button class="btn btn-dark"
                    onclick="location.href='http://127.0.0.1:8000/allauth/google/login/'">Login
                    with Google</button>

            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/accounts/signup.html
<!doctype html>
<html lang="en">
{% load static %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

        <link rel="stylesheet" href='{% static "/css/login.css" %}?{% now "U" %}'>
    <title>USER</title>
</head>
<body >
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'jobs:home' %}">NET Jobs</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            
            <li class="nav-item">
                {% if user.is_authenticated %}
                <form action=" {% url 'accounts:logout' %}" method="post">
                    {% csrf_token %}
                    <button class="btn btn-primary btn-sm" type="submit">Log Out</button>
                </form>
                {% endif %}
            </li>
           
          </ul>
          
        </div>
      </nav>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-6 mt-3">
            <h1>Signup</h1>
            <div class="form">
                <form id="signup" action="/accounts/signup/" method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <a href="{% url 'accounts:login' %}">Already have an account?</a>
                    <input class='btn btn-primary' type="submit" value="Signup">
                </form>
                <button class="btn btn-primary"
                    onclick="location.href='http://127.0.0.1:8000/allauth/google/login/'">Signup with Google</button>
            </div>
        </div>
    </div>
</div>



<!--
    <div class="container-fluid">
    <div class="row">
        <div class="col-md-6 col-lg-4">
            <h1>Log In</h1>
            <div class="form">
                <form id="login" action="{% url 'accounts:login' %}" method="post">
                    {% csrf_token %}
                    {{ form.as_p }}

                    <a href="{% url 'accounts:signup' %}">Dont have an account?</a>
                    <div class="submit">
                        <input type="submit" class="btn btn-primary" value="Log In">
                    </div>
                </form>
                <div class="loginwithgoogle">
                    <button class="btn btn-primary"
                        onclick="location.href='http://127.0.0.1:8000/allauth/google/login/'">Login
                        with Google</button>
                </div>
            </div>
        </div>
    </div>
</div>
-->

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <title>NET Jobs</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/custom-bs.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.fancybox.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-select.min.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/line-icons/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">    
  </head>
  <body id="top">


    <div class="site-wrap">
    
        <div class="site-mobile-menu site-navbar-target">
          <div class="site-mobile-menu-header">
            <div class="site-mobile-menu-close mt-3">
              <span class="icon-close2 js-menu-toggle"></span>
            </div>
          </div>
          <div class="site-mobile-menu-body"></div>
        </div> <!-- .site-mobile-menu -->
        
    
        <!-- NAVBAR -->
        <header class="site-navbar mt-3" >
          <div class="container-fluid" >
            <div class="row align-items-center" >
              <div class="site-logo col-6 "><a class="effect-shine" href="{% url 'jobs:home' %}">NET Jobs</a></div>
    
              <nav class="mx-auto site-navigation">
                <ul class="site-menu js-clone-nav d-none d-xl-block ml-0 pl-0">
                  <li><a href="{% url 'jobs:home' %}" class="nav-link active">Home</a></li>
                  <li><a href="{% url 'jobs:about' %}">About us</a></li>
                  <li><a href="{% url 'jobs:profile' %}">Profile</a></li>

                </ul>
              </nav>
              
              <div class="right-cta-menu text-right d-flex aligin-items-center col-6">
                <div class="ml-auto">
                  {% if user.is_authenticated %}
                  <form action="{% url 'accounts:logout' %}" method="POST">
                    {% csrf_token %}
                    <!-- <a href="{% url 'accounts:logout' %}" >Logout</a> -->
                    <button class="btn btn-primary border-width-2 d-none d-lg-inline-block" type="submit">Log Out</button>
                   
                   </form>
               
                  {% else %}
                  <a href="{% url 'accounts:login' %}" class="btn btn-primary border-width-2 d-none d-lg-inline-block">Login</a>
                  <a href="{% url 'accounts:signup' %}" class="btn btn-primary border-width-2 d-none d-lg-inline-block">Sign Up</a>
                  
                  {% endif %}
                 </div>
                <a href="#" class="site-menu-toggle js-menu-toggle d-inline-block d-xl-none mt-lg-2 ml-3"><span class="icon-menu h3 m-0 p-0 mt-2"></span></a>
              </div>
    
            </div>
          </div>
        </header>

   {% block body %}
   
   {% endblock %}
<!-- ======= Footer ======= -->
<footer id="footer" style="background: #242424 !important; text-align: center;padding: 1em;">
  <div class="container">
    <h3 style="color:azure">NET Jobs</h3>
    <div class="social-links">
      <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
      <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
      <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
      <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
      <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
    </div>
    <div class="copyright">
      &copy; Copyright <strong><span>NET Jobs</span></strong>. All Rights Reserved
    </div>
  </div>
</footer><!-- End Footer -->

</div>

  <!-- SCRIPTS -->
  
  
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js."></script>
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'js/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'js/stickyfill.min.js' %}"></script>
  <script src="{% static 'js/jquery.fancybox.min.js' %}"></script>
  <script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
  
  
  <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
  <script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
  <script src="{% static 'js/owl.carousel.min.js"></script>
  
  <script src="{% static 'js/custom.js' %}"></script>
   
  
  
   
</body>
</html>

templates/jobs/index.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <title>NET Jobs</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/custom-bs.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.fancybox.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-select.min.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/line-icons/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">    
  </head>
  <body id="top">


    <div class="site-wrap">
    
        <div class="site-mobile-menu site-navbar-target">
          <div class="site-mobile-menu-header">
            <div class="site-mobile-menu-close mt-3">
              <span class="icon-close2 js-menu-toggle"></span>
            </div>
          </div>
          <div class="site-mobile-menu-body"></div>
        </div> <!-- .site-mobile-menu -->
        
    
        <!-- NAVBAR -->
        <header class="site-navbar mt-3" >
          <div class="container-fluid" >
            <div class="row align-items-center" >
              <div class="site-logo col-6 "><a class="effect-shine" href="{% url 'jobs:home' %}">NET Jobs</a></div>
    
              <nav class="mx-auto site-navigation">
                <ul class="site-menu js-clone-nav d-none d-xl-block ml-0 pl-0">
                  <li><a href="{% url 'jobs:home' %}" class="nav-link active">Home</a></li>
                  <li><a href="{% url 'jobs:about' %}">About us</a></li>
                  {% if user.is_authenticated %}
                  <li><a href="{% url 'jobs:profile' %}">Profile</a></li>
                  
                  {% endif %}
                </ul>
              </nav>
              
              <div class="right-cta-menu text-right d-flex aligin-items-center col-6">
                <div class="ml-auto">
                  {% if user.is_authenticated %}
                  
                  <form action="{% url 'accounts:logout' %}" method="POST">
                    {% csrf_token %}
                    <!-- <a href="{% url 'accounts:logout' %}" >Logout</a> -->
                    <button class="btn btn-primary border-width-2 d-none d-lg-inline-block" type="submit">Log Out</button>
                    <label class="switch">
                      <input id="dark" type="checkbox">
                      <span class="slider round"></span>
                    </label>
                   </form>
               
                  {% else %}
                  <a href="{% url 'accounts:login' %}" class="btn btn-primary border-width-2 d-none d-lg-inline-block" >Login</a>
                  <a href="{% url 'accounts:signup' %}" class="btn btn-primary border-width-2 d-none d-lg-inline-block">Sign Up</a>
                  <label class="switch">
                    <input id="dark" type="checkbox">
                    <span class="slider round"></span>
                  </label>
                  {% endif %}
                 </div>
                <a id="collapse"href="#" class="site-menu-toggle js-menu-toggle d-inline-block d-xl-none mt-lg-2 ml-3"><span class="icon-menu h3 m-0 p-0 mt-2"></span></a>
              </div>
    
            </div>
          </div>
        </header>
    <!-- HOME -->
    <section class="home-section section-hero overlay bg-image"  id="home-section">

      <div class="container">
        <div class="row align-items-center justify-content-center">
          <div class="col-md-12">
            <div class="mb-5 text-center">
              <h1 class=" font-weight-bold" style="color:white;font-weight: bolder;">Your Dream Job is Waiting</h1>
              <p style="color:white;font-weight: bolder;">Find your dream jobs on our powerful career website.</p>
            </div>
            <form action="{% url 'jobs:result'%}"method="post" class="search-jobs-form">  
              {% csrf_token %}
              <div class="row mb-5" style="justify-content: center;">
                <div class="col-12 col-sm-6 col-md-6 col-lg-3 mb-4 mb-lg-0">
                  <select name='jobp'  class="form-control">
                    <option value="Job Profile">Job Profile</option>
                    <option value="Software Developer">Software Developer</option>
                    <option value="Accountant">Accountant</option>
                    <option value="Web Developer">Web Developer</option>
                    <option value="Data Analyst">Data Analyst</option>
                    <option value="Data Scientist">Data Scientist</option>
                    <option value="Android Developer">Android Developer</option>
                    <option value="Java Developer">Java Developer</option>
                    <option value="UX designer">UX designer</option>
                    <option value="Technical sales engineer">Technical sales engineer</option>
                    <option value="Retail manager">Retail manager</option>
                    <option value="IT consultant">IT consultant</option>
                    
                    <option value="Graphic designer">Graphic designer</option>
                    
                    
                  </select>
                </div>
                <div class="col-12 col-sm-6 col-md-6 col-lg-3 mb-4 mb-lg-0">
                  <select name='jobl'class="form-control">
                    <option value="Location" >Location</option>
                    <option value="Bangalore">Bangalore</option>
                    <option value="Gurugram">Gurugram</option>
                    <option value="Noida">Noida</option>
                    <option value="Hyderabad">Hyderabad</option>
                    <option value="Mumbai">Mumbai</option>
                    <option value="Orissa">Orissa</option>
                    <option value="Pune">Pune</option>
                    <option value="Delhi">Delhi</option>
                    <option value="Surat">Surat</option>
                    <option value="Jaipur">Jaipur</option>
                    <option value="Patna">Patna</option>
                    <option value="Jalandhar">Jalandhar</option>
                    <option value="Lucknow">Lucknow</option>
                    <option value="Goa">Goa</option>
                    <option value="Amritsar">Amritsar</option>
                  </select>
                </div>
               
                <div class="col-12 col-sm-6 col-md-6 col-lg-3 mb-4 mb-lg-0">
                  <button type="submit" class="btn btn-primary btn-lg btn-block text-white btn-search"><span class="icon-search icon mr-2"></span>Search Job</button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>

      
    </section>

    <section id= "darkmode" class="site-section">
      <div class="container">

        <div class="row mb-5 justify-content-center">
          <div class="col-md-7 text-center">
            <h2 class="section-title mb-2">Your Search Results</h2>
          </div>
        </div>

       
        <div class="mb-5 go">
          {% for id,title,comapny,summary,date,link in data %}
          <div class="row align-items-start job-item border-bottom pb-3 mb-3 pt-3">
            <!-- <div class="col-md-2">
              <a href="job-single.html"><img src="images/featured-listing-1.jpg" alt="Image" class="img-fluid"></a>
            </div> -->
           

            
            <div class="col-md-4">
              <span id ="job{{id}}" class="badge badge-primary px-2 py-1 mb-3">{{job}}</span>
              
              
              <h2 id="title{{id}}" class="headi" >{{title}}</h2>
              <p class="mt-1"><span class="badge badge-secondary px-2 py-1 mb-3 mr-1">Company</span><strong id="company{{id}}" class="com"style="text-align: justify;">{{comapny}}</strong> </p>
            </div>

            <div class="col-md-3 text-left">
              <span class="badge badge-primary px-2 py-1 mb-3">Location</span>
              <p><span id="location{{id}}" class="loc" style="text-align: justify;">{{location}}</span></p>
            </div>

            <div class="col-md-3 text-left">
              <span class="badge badge-primary px-2 py-1 mb-3">Job Description</span>
              <p><span style="text-align: justify;"class="sum">{{summary}}</span></p>
            </div>

            <div class="col-md-2 text-center">
              <!-- <h3>Job Description</h3>
              <span style="color:black;text-align: justify;">{{summary}}</span> -->
              <span class="badge badge-success"><a id="apply{{id}}" href="{{link}}" onclick="getData('{{id}}')" target="_blank" style="text-decoration: none;color:white;font-size:1.1em;">Apply Now</a></span>
            </div>
           
          </div>

         {% endfor %}

          


      <div class="row pagination-wrap"  style="justify-content: center;">

      <div class="text-center text-md-left">
            <div class="custom-pagination ml-auto">  
              {% if data.has_previous %}

                <a href="?page=1" class="prev"><<</a>
                <a href="?page={{data.previous_page_number }}" class="prev ml-auto">Previous</a>
              {% endif %}
              <div class="d-inline-block">
              {% for num in data.paginator.page_range %}
                {% if data.number == num %}
                <button class="btn btn-dark" disabled>{{ num }}</button>
                {% elif num > data.number|add:'-7' and num < data.number|add:'7' %}
                <button class="btn btn-light" onclick='location.href="?page={{num}}"'> {{ num }}</button>
                {% endif %}
              {% endfor %}
              </div>
              {% if data.has_next %}
                <a href="?page={{ data.next_page_number }}" class="next ml-auto">Next</a>
                <a href="?page={{ data.paginator.num_pages }}" class="next ml-auto">>></a>
              {% endif %}
              </div>
          </div>
      </div>
       
          
          
          

      
    </section>
    {% if user.is_authenticated %}
    {% else %}
    <section class="py-5 bg-image overlay-primary fixed overlay" style="background-image: url('images/hero_1.jpg');">
      <div class="container">
        <div class="row align-items-center">
          <div class="col-md-8">
            <h2 class="text-white">Looking For A Job?</h2>
            <p class="mb-0 text-white lead">We provide the best job searching website.</p>
          </div>
          <div class="col-md-3 ml-auto">
            <a href="{% url 'accounts:signup' %}" class="btn btn-warning btn-block btn-lg">Sign Up</a>
          </div>
        </div>
      </div>
    </section>


<!-- Button trigger modal -->







    {% endif %}
    <footer id="footer" style="background: #242424 !important; text-align: center;padding: 1em;">
      <div class="container">
        <h3 style="color:azure">NET Jobs</h3>
        <div class="social-links">
          <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
          <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
          <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
          <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
          <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
        </div>
        <div class="copyright">
          &copy; Copyright <strong><span>NET Jobs</span></strong>. All Rights Reserved
        </div>
      </div>
    </footer><!-- End Footer -->
    
    </div>


 <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js."></script>
 <script src="{% static 'js/jquery.min.js' %}"></script>
 <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
 <script src="{% static 'js/isotope.pkgd.min.js' %}"></script>
 <script src="{% static 'js/stickyfill.min.js' %}"></script>
 <script src="{% static 'js/jquery.fancybox.min.js' %}"></script>
 <script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
 
 
 <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
 <script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
 <script src="{% static 'js/owl.carousel.min.js"></script>
 
 <script src="{% static 'js/custom.js' %}"></script>
 
 <script type="text/javascript">
   
  function getData(id)
  {
    
    var com=document.getElementById("company"+id).innerText;
    var loc=document.getElementById("location"+id).innerText;
    var title=document.getElementById("title"+id).innerText;
    var link=document.getElementById("apply"+id).href;
    $.ajax({
    type:'POST',
    url:"{% url 'jobs:profiledata'%}",
    data:{'company':com,'location':loc,'title':title,'link':link, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
    dataType:'json',
    
    success:function(response){
      console.log(response)
      

    }
  });
  
  return false;
  }


$("#dark").click(function() {
  console.log("yes");
  if($(this).is(":checked")){
    $("#darkmode").addClass('justdo');
  }    
  else{
    $("#darkmode").removeClass('justdo');
  }
  
  }).change();


</script>

   
</body>
</html>